defaults: &defaults
  docker:
    - image: cimg/node:lts-browsers

version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

            # This is where "puppeteer" test suite downloads Chrome binaries
            # when the package is installed. When "node_modules" folder is
            # restored from the cache, the "puppeteer" does not have to be
            # reinstalled, thus it won't re-download Chrome, by default,
            # and thus we better save this cache folder.
            - ~/.cache/puppeteer

      - run: npm run build
      - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - build
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - test
